# Generated by Django 4.1.1 on 2022-10-04 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_id', models.CharField(blank=True, max_length=50, null=True)),
                ('equipment_type', models.CharField(choices=[('1', 'Laptop'), ('2', 'Desktop'), ('3', 'Networking Device'), ('4', 'Mouse'), ('5', 'Access Point'), ('6', 'Printer'), ('7', 'Scanner'), ('8', 'CCTV')], max_length=50)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('ram', models.CharField(blank=True, max_length=100, null=True)),
                ('storage', models.CharField(blank=True, max_length=100, null=True)),
                ('display_size', models.CharField(blank=True, max_length=100, null=True)),
                ('paper_size', models.CharField(blank=True, max_length=100, null=True)),
                ('operating_system', models.CharField(blank=True, max_length=100, null=True)),
                ('is_visible', models.IntegerField(default=1)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('is_visible', models.IntegerField(default=1)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VendorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.CharField(blank=True, max_length=50, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=500, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('email_id', models.CharField(blank=True, max_length=500, null=True)),
                ('address', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_visible', models.IntegerField(default=1)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_order_number', models.IntegerField(blank=True, null=True)),
                ('purchase_request_number', models.IntegerField(blank=True, null=True)),
                ('delivery_no', models.IntegerField(blank=True, null=True)),
                ('delivery_equipment', models.CharField(blank=True, max_length=500, null=True)),
                ('delivery_quantity', models.IntegerField(blank=True, null=True)),
                ('warranty_start_date', models.DateField()),
                ('warranty_end_date', models.DateField()),
                ('is_visible', models.IntegerField(default=1)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('equipment_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.equipmentmaster')),
                ('invoice_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.invoicemaster')),
                ('vendor_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.vendordetails')),
            ],
        ),
        migrations.CreateModel(
            name='MasterInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_code', models.CharField(blank=True, max_length=30, null=True)),
                ('equipment_id', models.CharField(blank=True, max_length=50, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=10, null=True)),
                ('employee_name', models.CharField(blank=True, max_length=100, null=True)),
                ('warranty_start_date', models.DateField()),
                ('warranty_end_date', models.DateField()),
                ('purchase_order_number', models.CharField(blank=True, max_length=30, null=True)),
                ('is_visible', models.IntegerField(default=1)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TimeField()),
                ('is_visible', models.IntegerField(default=1)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('is_visible', models.IntegerField(default=1)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
