# Generated by Django 4.1.1 on 2022-10-06 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentcategory',
            options={'verbose_name_plural': 'Equipment Categories '},
        ),
        migrations.AlterModelOptions(
            name='equipmentmaster',
            options={'verbose_name_plural': 'Equipment Master'},
        ),
        migrations.AlterModelOptions(
            name='equipmentsubcategory',
            options={'verbose_name_plural': 'Equipment Subcategories'},
        ),
        migrations.AlterModelOptions(
            name='invoicemaster',
            options={'verbose_name_plural': 'Invoice Master'},
        ),
        migrations.AlterModelOptions(
            name='masterinventory',
            options={'verbose_name_plural': 'Master Inventory'},
        ),
        migrations.AlterModelOptions(
            name='orderdetails',
            options={'verbose_name_plural': 'Order Details'},
        ),
        migrations.AlterModelOptions(
            name='vendordetails',
            options={'verbose_name_plural': 'Vendor Details'},
        ),
        migrations.AddField(
            model_name='masterinventory',
            name='equipment_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.equipmentmaster'),
        ),
    ]
