# Generated by Django 4.1.1 on 2022-10-06 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_equipmentcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentcategory',
            options={'verbose_name_plural': 'Equipment Categories'},
        ),
        migrations.AddField(
            model_name='equipmentcategory',
            name='equipment_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.equipmentmaster'),
        ),
    ]
