# Generated by Django 4.1.1 on 2022-10-07 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_equipmentcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentsubcategory',
            name='equipment_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.equipmentmaster', verbose_name='Equipment name'),
        ),
        migrations.AlterField(
            model_name='equipmentcategory',
            name='equipment_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.equipmentmaster', verbose_name='Equipment name'),
        ),
    ]
