# Generated by Django 4.1.1 on 2022-10-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_equipmentsubcategory_equipment_master_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentcategory',
            name='equipment_master',
        ),
        migrations.AddField(
            model_name='equipmentcategory',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentcategory',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
