# Generated by Django 4.1.1 on 2022-10-13 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_purchaseorders_orderdetails_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='purchaseorders',
            name='equipment_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.equipmentmaster', verbose_name='Equipment name'),
        ),
        migrations.AddField(
            model_name='purchaseorders',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.vendordetails'),
        ),
        migrations.AlterField(
            model_name='purchaseorders',
            name='purchase_order_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='PurchaseRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_request_number', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_request_date', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.employeemaster')),
                ('equipment_master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.equipmentmaster', verbose_name='Equipment name')),
            ],
        ),
    ]
