# Generated by Django 4.1.1 on 2022-10-25 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_employeemaster_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeemaster',
            options={'verbose_name_plural': '05. Employee Master'},
        ),
        migrations.AlterModelOptions(
            name='equipmentcategory',
            options={'verbose_name_plural': '03. Equipment Categories'},
        ),
        migrations.AlterModelOptions(
            name='equipmentmaster',
            options={'verbose_name_plural': '02. Equipment Master'},
        ),
        migrations.AlterModelOptions(
            name='equipmentsubcategory',
            options={'verbose_name_plural': '04. Equipment Subcategories'},
        ),
        migrations.AlterModelOptions(
            name='invoicemaster',
            options={'verbose_name_plural': '10. Invoice Master'},
        ),
        migrations.AlterModelOptions(
            name='masterinventory',
            options={'verbose_name_plural': '01. Master Inventory'},
        ),
        migrations.AlterModelOptions(
            name='orderdetails',
            options={'verbose_name_plural': '08. Order Details'},
        ),
        migrations.AlterModelOptions(
            name='purchaseorders',
            options={'verbose_name_plural': '07. Purchase Orders'},
        ),
        migrations.AlterModelOptions(
            name='purchaserequests',
            options={'verbose_name_plural': '06. Purchase Requests'},
        ),
        migrations.AlterModelOptions(
            name='vendordetails',
            options={'verbose_name_plural': '09. Vendor Details'},
        ),
    ]
