# Generated by Django 4.1.1 on 2022-10-31 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_masterinventory_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentsubcategory',
            name='equipment_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.equipmentcategory'),
        ),
        migrations.AlterField(
            model_name='equipmentmaster',
            name='equipment_type',
            field=models.CharField(choices=[('0', 'Desktop'), ('1', 'Networking device'), ('2', 'Mouse'), ('3', 'Access Point'), ('4', 'Printer'), ('5', 'Scanner'), ('6', 'CCTV'), ('7', 'Alexa')], max_length=50),
        ),
    ]
