# Generated by Django 4.1.1 on 2022-10-31 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_equipmentsubcategory_equipment_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentsubcategory',
            name='equipment_master',
        ),
        migrations.AddField(
            model_name='equipmentsubcategory',
            name='equipment_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentsubcategory',
            name='description',
            field=models.TextField(),
        ),
    ]
