# Generated by Django 4.1.1 on 2023-01-29 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_userprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicemaster',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.equipmentmaster'),
        ),
    ]
