# Generated by Django 4.1.1 on 2023-02-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_invoicemaster_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicemaster',
            name='delivery_challan',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
