# Generated by Django 4.1.1 on 2023-02-12 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_invoicemaster_delivery_challan_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicemaster',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.vendordetails'),
        ),
    ]
