# Generated by Django 4.1.1 on 2023-03-02 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_invoicemaster_vendor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EquipmentSubcategory',
        ),
    ]
