# Generated by Django 4.1.1 on 2023-03-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_purchaseorders_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemaster',
            name='email_id',
            field=models.EmailField(blank=True, max_length=500, null=True),
        ),
    ]
