# Generated by Django 4.1.1 on 2023-04-23 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0024_alter_employeemaster_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='action',
            field=models.CharField(default='', editable=False, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditlog',
            name='additional_info',
            field=models.TextField(default='', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditlog',
            name='subject',
            field=models.CharField(default='', editable=False, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
